# Generated by Django 4.2 on 2023-09-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=50, unique=True)),
                ('menu_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='languagechoice',
            name='translation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.languagechoice')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translatedmenu')),
            ],
        ),
        migrations.AddField(
            model_name='translatedmenu',
            name='translations',
            field=models.ManyToManyField(through='main.Translation', to='main.languagechoice'),
        ),
    ]
