# Generated by Django 4.2 on 2023-09-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_translatedmenu_languagechoice_translation_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagechoice',
            name='translation_enabled',
        ),
    ]
