# Generated by Django 4.2 on 2023-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_languagechoice_translation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedmenu',
            name='detail_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='translatedmenu',
            name='image_url',
            field=models.URLField(default='https://s3.us-east-1.amazonaws.com/hyunday-file/1694438095296-Avatar.png'),
        ),
    ]
