# Generated by Django 4.2 on 2023-09-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_translatedmenu_detail_url_translatedmenu_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu_name', models.CharField(max_length=50)),
                ('image_url', models.URLField(default='https://s3.us-east-1.amazonaws.com/hyunday-file/1694438095296-Avatar.png')),
                ('detail_url', models.URLField(default='')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='main.translatedmenu')),
            ],
        ),
        migrations.CreateModel(
            name='SubTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.languagechoice')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.submenu')),
            ],
        ),
        migrations.AddField(
            model_name='submenu',
            name='translation',
            field=models.ManyToManyField(through='main.SubTranslation', to='main.languagechoice'),
        ),
    ]
